classDiagram
class Loan {
    - id
    - book
    - dueDate
    - returnDate
    - loanDate
    + loan(book, user, dueDate, returnDate, loanDate)
    + renew(newDueDate)
    + return()
    + isOverDue()
}

class Notification {
    <<interface>>
    + notify(loan)
}

class EmailNotifer {
    + notify(loan)
}

Loan --> Notification: usa
EmailNotifier ..|> Notification : implementa