flowchart TD
subgraph TD["API"]
Catalog["Catálogo<br>listar e buscar livros"]
Loan["Empréstimo<br>empresta e devolve livros"]
Notification["Notificação<br>monitora e notifica prazo"]
end

Email["Disparador de e-mails (serviço externo)"]

Loan -->|consulta| Catalog
Loan -->|aciona| Notification
Notification -->|chama| Email
